### ISSUE TITLE
Contributing => Segíts te is

### ISSUE THREAD

**Issue by mrbig** [HatalyakMate/betaflight-configurator#2]
Nyitó oldalon a `contributing`-ot "Hozzájárult"-nak fordítottad.

Helyette valami ilyesmit javasolnék: "Segíts te is", vagy "Segítsen ön is!", esetleg: "Hozzájárulása fontos számunkra" Mivel van hely, nem gond ha kicsit hosszabb a szöveg, ezt az egy szavas kifejezést nehéz lefordítani magyarul egy szóban.

**Comment by HatalyakMate** [comment]
Javítva
