### ISSUE TITLE
repülésirányító => repülésvezérlő

### ISSUE THREAD

**Issue by mrbig** [HatalyakMate/betaflight-configurator#3]
A flight controllert én repülésvezérlőnek fordítanám. A szakzsargonban általában a vezérlés vagy a szabályozás kifejezést használják, az irányítás alatt mást értünk kicsit.

Tipp: a pid controllert magyarul pid szabályozónak, vagy csak szabályozókörnek szoktuk hívni (nem látom mire fordítottad)

**Comment by HatalyakMate** [comment]
Javítva mindenhol
